canEnforceMinimumPythonVersion = true
condaSolveImplementation = hawk
enableCodeAssistEnvironmentCaching = true
enableLegacyFallback = false
envPackingLogicVersion = 2
org.gradle.caching = true
org.gradle.vfs.watch = false
palantirModelsVersion = 0.2353.0
rootProjectName = rensic-ingestion
systemProp.http.connectionTimeout = 600000
systemProp.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.connectionTimeout = 600000
systemProp.org.gradle.internal.http.socketTimeout = 600000
transformsDefaultBranchName = master
transformsLangPythonPluginVersion = 1.1182.0
transformsRepoOrg = George Gorzhiyev-a8216a
transformsRepoPath = /George Gorzhiyev-a8216a/Rensic/data-integration/code-repositories/rensic-ingestion
transformsRepoProject = Rensic
transformsRepoRid = ri.stemma.main.repository.62965e3e-8236-4a2f-a3de-c49ec2093a68
transformsVersion = 10.160.0
useCondaLocksForPlatforms = linux-64
useDefaultPython = false
useHawkAsDefaultSolver = true
useHawkUvSolver = true
useIncrementalSolve = true
