functionsTypescriptRuntimeVersion = 0.45.0
functionsTypescriptVersion = 0.1314.0
functionsVersion = 3.1192.0
nodeInstallationVersion = 24.16.0
repositoryName = rensic-functions
repositoryOrg = George Gorzhiyev-a8216a
repositoryProject = Rensic
repositoryRid = ri.stemma.main.repository.3510bc15-8b1d-46ba-bd56-1d64c5dcd698
